version: '3.8'

services:
  web:
    build: .
    container_name: breaker-app
    network_mode: host
    environment:
      - UPLOAD_DIR=data/images/raw_uploads
      - INFERENCE_URL=http://192.168.1.147:8080/predict
    volumes:
      - ./data:/app/data
      - ./app/app/frontend:/app/app/frontend
    restart: always

  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    network_mode: host
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
